# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bhawanshsingh/Desktop/task

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bhawanshsingh/Desktop/task

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bhawanshsingh/Desktop/task/CMakeFiles /Users/bhawanshsingh/Desktop/task//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bhawanshsingh/Desktop/task/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named StudentManagementSystem

# Build rule for target.
StudentManagementSystem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StudentManagementSystem
.PHONY : StudentManagementSystem

# fast build rule for target.
StudentManagementSystem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/build
.PHONY : StudentManagementSystem/fast

src/core/Logger.o: src/core/Logger.cpp.o
.PHONY : src/core/Logger.o

# target to build an object file
src/core/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/core/Logger.cpp.o
.PHONY : src/core/Logger.cpp.o

src/core/Logger.i: src/core/Logger.cpp.i
.PHONY : src/core/Logger.i

# target to preprocess a source file
src/core/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/core/Logger.cpp.i
.PHONY : src/core/Logger.cpp.i

src/core/Logger.s: src/core/Logger.cpp.s
.PHONY : src/core/Logger.s

# target to generate assembly for a file
src/core/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/core/Logger.cpp.s
.PHONY : src/core/Logger.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/service/StudentService.o: src/service/StudentService.cpp.o
.PHONY : src/service/StudentService.o

# target to build an object file
src/service/StudentService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/service/StudentService.cpp.o
.PHONY : src/service/StudentService.cpp.o

src/service/StudentService.i: src/service/StudentService.cpp.i
.PHONY : src/service/StudentService.i

# target to preprocess a source file
src/service/StudentService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/service/StudentService.cpp.i
.PHONY : src/service/StudentService.cpp.i

src/service/StudentService.s: src/service/StudentService.cpp.s
.PHONY : src/service/StudentService.s

# target to generate assembly for a file
src/service/StudentService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/service/StudentService.cpp.s
.PHONY : src/service/StudentService.cpp.s

src/ui/CLI.o: src/ui/CLI.cpp.o
.PHONY : src/ui/CLI.o

# target to build an object file
src/ui/CLI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/ui/CLI.cpp.o
.PHONY : src/ui/CLI.cpp.o

src/ui/CLI.i: src/ui/CLI.cpp.i
.PHONY : src/ui/CLI.i

# target to preprocess a source file
src/ui/CLI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/ui/CLI.cpp.i
.PHONY : src/ui/CLI.cpp.i

src/ui/CLI.s: src/ui/CLI.cpp.s
.PHONY : src/ui/CLI.s

# target to generate assembly for a file
src/ui/CLI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StudentManagementSystem.dir/build.make CMakeFiles/StudentManagementSystem.dir/src/ui/CLI.cpp.s
.PHONY : src/ui/CLI.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... StudentManagementSystem"
	@echo "... src/core/Logger.o"
	@echo "... src/core/Logger.i"
	@echo "... src/core/Logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/service/StudentService.o"
	@echo "... src/service/StudentService.i"
	@echo "... src/service/StudentService.s"
	@echo "... src/ui/CLI.o"
	@echo "... src/ui/CLI.i"
	@echo "... src/ui/CLI.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

